### ISSUE TITLE
showcase/entertainment scripts

### ISSUE THREAD

**Issue by JukoiDev** [fosslife/awesome-ricing#23]
i suggest new category - showcase and fun scripts:
[cmatrix](https://github.com/abishekvashok/cmatrix) - matrix
[pipes]() - script which generates colorful lines
[cbonsai](https://aur.archlinux.org/packages/cbonsai-git) - tree growing animation with you own text

**Comment by siduck** [comment]
@JukoiDev make a PR for it! 

add another section called "Show off scripts"

**Comment by JukoiDev** [comment]
sure
