### ISSUE TITLE
[✨] Feature: Windows, MacOs

### ISSUE THREAD

**Issue by TheElegantCoding** [fosslife/awesome-ricing#46]
Hello, it will be nice if somehow we can split the softwares between OS, like windows managers for MacOs only

**Comment by siduck** [comment]
sounds good to me, PR's are welcome!

**Comment by TheElegantCoding** [comment]
for now i will close this issue, i love how this readme is growing and i see a lot of mac and windows support added, this way we can filter that data

**Comment by siduck** [comment]
i'm no longer in control of this repo !
