### ISSUE TITLE
new fetches

### ISSUE THREAD

**Issue by Sparkenstein** [fosslife/awesome-ricing#9]
Found out these new fetches:
priority:
 - https://github.com/TheDarkBug/uwufetch
 - https://github.com/M4cs/winfetch (another winfetch)
 - https://github.com/Smirnov-O/gf
 - https://github.com/Macchina-CLI/macchina
 - https://github.com/NNBnh/bfetch

less priority (decide if you want them they are not popular):
 - https://github.com/sudosmile/smilefetch
 - https://github.com/NoSequel/efetch
 - https://github.com/vereis/erlfetch

**Comment by siduck76** [comment]
I dont see anything new in smilefetch and efetch , so adding it wouldnt be good I think
